---
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 7179a42b3544e953e3683a670056ad385892365d
    hooks:
      - id: commitizen
        stages: [commit-msg]
      - id: commitizen-branch
        stages: [pre-push]
