[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.10.0"]

[dependency-groups]
build = [
    "pyinstaller>=6.19.0",
]
dev = [
    "commitizen>=4.13.8",
    "prek>=0.3.4",
    "ruff>=0.15.2",
    "ty>=0.0.17",
]
docs = [
    "mkdocstrings-python>=2.0.3",
    "typer>=0.24.0",
    "zensical>=0.0.23",
]
tests = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]

[project]
authors = [
    { name = "Gabriel Santos de Souza", email = "gabriel.santosdesouza@dcomp.ufs.br" }
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Framework :: Pydantic",
  "Framework :: Pytest",
  "Intended Audience :: End Users/Desktop",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Programming Language :: Python :: 3.12",
  "Topic :: Internet",
  "Topic :: Multimedia",
  "Topic :: Terminals",
  "Topic :: Text Processing",
  "Topic :: Utilities",
  "Typing :: Typed",
]
dependencies = [
    "av>=16.1.0",
    "brotli>=1.2.0",
    "bs4>=0.0.2",
    "courlan>=1.3.2",
    "lxml>=6.0.2",
    "pydantic>=2.12.5",
    "pymupdf>=1.27.1",
    "python-magic>=0.4.27; sys_platform != 'win32'",
    "python-magic-bin>=0.4.14; sys_platform == 'win32'",
    "regex>=2026.2.19",
    "trafilatura>=2.0.0",
    "typer>=0.24.0",
    "yt-dlp>=2026.2.21",
    "zstandard>=0.25.0",
]
description = "Content consumption analyzer CLI"
license = "GPL-3.0-or-later"
name = "consumo"
readme = "README.md"
requires-python = ">=3.12"
version = "0.6.1"

[project.scripts]
consumo = "consumo.cli.main:app"

[tool.commitizen]
breaking_change_exclamation_in_title = true
major_version_zero = true
name = "cz_conventional_commits"
tag_format = "$version"
update_changelog_on_bump = true
version_scheme = "pep440"
version_provider = "uv"

[tool.pytest.ini_options]
addopts = "--cov --cov-branch --cov-report=xml --import-mode=importlib --junitxml=junit.xml --maxfail=1 -o junit_family=legacy"

[tool.ruff]
fix = true

[tool.ruff.lint]
extend-select = ["ANN", "D", "I"]

[tool.ruff.lint.pydocstyle]
convention = "google"
