name: CI

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - .github/actions/tests/action.yaml
      - .github/workflows/ci.yaml
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Test
      uses: ./.github/actions/tests
    - name: Codecov Coverage
      uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
    - name: Codecov Tests
      uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
      with:
        report_type: test_results
