name: Publish

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Install uv
      uses: astral-sh/setup-uv@ed21f2f24f8dd64503750218de024bcf64c7250a
      with:
        version: "0.9.14"
    - name: Publish
      run: uv publish
